# typings/bottle.pyi

from typing import Any, Callable

def run(*args: Any, **kwargs: Any) -> None: ...
def template(*args: Any, **kwargs: Any) -> str: ...
def static_file(*args: Any, **kwargs: Any) -> Any: ...

def route(path: str, method: str = "GET", **options: Any) -> Callable[..., Any]: ...
def get(path: str, **options: Any) -> Callable[..., Any]: ...
def post(path: str, **options: Any) -> Callable[..., Any]: ...
